spring:
  application:
    name: Admin-portal
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379

server:
  port: 8084
  servlet:
    context-path: /user

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.security: DEBUG

jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: "false"
  hibernate:
    ddl-auto: 'create-drop'

email:
  smtp:
    username: '<ENTER_USERNAME/GMAIL>'
    host: '<ENTER_HOST>'
    password: '<ENTER_PASSWORD>'
    port: 587
  mailType: html
  charset: iso-8859-1
  wordwrap: TRUE
  active: "no-reply@carot.com"